language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -U setuptools"
  - "python setup.py install"
  - "pip install -U pytest pytest-pep8 coverage python-coveralls"
script: "coverage run --source busbus -m pytest --pep8"
after_script:
  - "coverage report -m"
  - "coveralls"
