language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
sudo: false
env:
  - "APSW_VERSION=3.8.8.2-r1"
before_install:
  - "gpg --keyserver hkp://keys.gnupg.net --recv-keys 02DA39A85354DD3D7343EFC198E39F1E0DFBD904"
  - "wget https://github.com/rogerbinns/apsw/releases/download/$APSW_VERSION/apsw-$APSW_VERSION.zip https://github.com/rogerbinns/apsw/releases/download/$APSW_VERSION/apsw-$APSW_VERSION-sigs.zip"
  - "unzip -d apsw-sigs apsw-$APSW_VERSION-sigs.zip && mv apsw-sigs/apsw-$APSW_VERSION.zip.asc ./ && gpg --verify apsw-$APSW_VERSION.zip.asc"
  - "unzip apsw-$APSW_VERSION.zip"
install:
  - "pip install -U pip setuptools"
  - "cd apsw-$APSW_VERSION && python setup.py fetch --all build --enable-all-extensions install test && cd .. && rm -rf apsw-$APSW_VERSION apsw-$APSW_VERSION.zip"
  - "pip install -e . -e .[dev] -e .[web]"
script: "coverage run --source busbus -m pytest --pep8"
after_script:
  - "coverage report -m"
  - "coveralls"
notifications:
  email: false
  slack:
    secure: CWJNMK/DvPKB31iDKXAPxaBQz6V2qZftFgTEqVaKbedF34rRGQK4R/OOobQ/PLbJ053tmgERWQl3L67ZeX06qS4PMy86LXv1Tvw5bcIiL7WebxtpCuZzWktVhCz14wtq+5kZXTyB/yT4C0IOoWXDHG0Fc6E9CseTMNT1V8MWNRM=
