language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "pip install -U setuptools"
  - "python setup.py install"
  - "pip install -U pytest pytest-cov python-coveralls"
script: "py.test --cov busbus --cov-report term-missing"
after_success: "coveralls"
